### ISSUE TITLE
Comparison of: String <= Integer, is not possible

### ISSUE THREAD

**Issue by alexjfisher** [treydock/puppet-module-kernel#1]
Hi
Future parser (as of puppet 3.7.4) doesn't like https://github.com/treydock/puppet-module-kernel/blob/master/manifests/params.pp#L11

See https://tickets.puppetlabs.com/browse/PUP-3615 for the change in puppet.

I could create a PR, but I was wondering what your plans were for this module?  Is RHEL7 support a work in progress?  Is it as simple (or perhaps difficult) as implementing the grub2 class?

Thanks,
Alex

**Comment by treydock** [comment]
@alexjfisher I'll fix the version comparison issue.

A PR for RHEL7 support would be great.  My hope was all that would be required is implementing the grub2 class.

**Comment by alexjfisher** [comment]
How about using `/sbin/grubby --set-default` to modify the grub config files?  I'll give this a go, but in theory, it might work equally well for both RHEL 6 and 7.
